### ISSUE TITLE
Successful execution of endpoint `/update_data` breaks endpoint `/predict_from_test`

### ISSUE THREAD

**Issue by omarchoa** [omarchoa/dec23_mlops_accidents#10]
```
INFO:     127.0.0.1:57141 - "GET /predict_from_test HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/src/features/api/api.py", line 210, in get_pred_from_test
    pred = rdf.predict(X_test.iloc[[i]])
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 905, in predict
    proba = self.predict_proba(X)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 947, in predict_proba
    X = self._validate_X_predict(X)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 641, in _validate_X_predict
    X = self._validate_data(
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/base.py", line 608, in _validate_data
    self._check_feature_names(X, reset=reset)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/base.py", line 535, in _check_feature_names
    raise ValueError(message)
ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- id_usager
```

**Comment by omarchoa** [comment]
### Stopgap solution
Replace the preprocessed CSV files generated by the endpoint `/update_data` with the ones generated by the original script `make_dataset.py` (downloadable [here](https://drive.google.com/drive/folders/11ComHHtBMydIii0LORiYtwg6hPbW3rp5?usp=drive_link)).
