### ISSUE TITLE
Successful execution of endpoint `/update_data` breaks endpoint `/train`

### ISSUE THREAD

**Issue by omarchoa** [omarchoa/dec23_mlops_accidents#11]
```
INFO:     127.0.0.1:58352 - "GET /train HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/src/features/api/api.py", line 360, in get_train
    rf_classifier.fit(X_train, y_train)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1263, in check_X_y
    X = check_array(
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 997, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/sklearn/utils/_array_api.py", line 521, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "/Users/omarchoa/GitHub/dec23_mlops_accidents/.venv/lib/python3.9/site-packages/pandas/core/generic.py", line 2150, in __array__
    arr = np.asarray(values, dtype=dtype)
ValueError: could not convert string to float: '175Â\xa0129'
```

**Comment by omarchoa** [comment]
### Stopgap solution
Replace the preprocessed CSV files generated by the endpoint `/update_data` with the ones generated by the original script `make_dataset.py` (downloadable [here](https://drive.google.com/drive/folders/11ComHHtBMydIii0LORiYtwg6hPbW3rp5?usp=drive_link)).
